# Author details.
jenn:
    name: Jenn Leung
    email: j.leung91@gmail.com
    gravatar: ed5471d2e20908a2e74b28a1a00a1519
    #web: http://twitter.com/sdasd
gabe:
    name: Gabe Grazier G'Sell
    email: gabergg@gmail.com
    gravatar: ed5471d2e20908a2e74b28a1a00a1519
    #web: http://twitter.com/sdad